### ISSUE TITLE
您好我尝试了一些方法，但无法成功运行该项目，请问我应该怎么做？

### ISSUE THREAD

**Issue by 1111msk** [Yarukon/WTDC-CN#1]
RT，不懂代码编程
1、根据您的安装提示，我找了相关教程并下载了BepInEx
复制到游戏根目录→运行游戏→得到plugins文件夹

我把您的汉化配置文件全部放到plugins里/游戏根目录，无法运行成功，有些情况可以触发某个文件？？游戏内排版明显变化，设置文字消失，没有任何中文信息

2、根据您的书面说明，我查阅了另一个作者xiaoye97的汉化插件I18NFont4UnityGame，根据说明放置文件（看不懂使用说明4、5、8）
无果，尝试了一些路径，同无果，我不理解他说的修改dll
我联系xiaoye97，他的回答是您有自己的汉化插件，且我不理解的568条使用说明是给开发者看的而不是面对玩家

2.5我去您的主页翻看了其他框架？（我不知道github用户如何称呼它，code？代码？？）
并没有找到您自己制作的汉化插件 ，其他文件似乎大都是c语言类

3、依然没搞懂，搜索资料找到，XUnity Auto Translator插件（我当时不知道您用的是否是这个，我以为这个是和bepinex捆绑的组合汉化插件）
视频教学https://www.bilibili.com/video/BV1Gg411h7Eq/?vd_source=6088393aaf349903225b0e58b5258efb
我把您的字体和他的教学串在一起
结果发现必须开着梯子实时翻译，和您的插件似乎没有直接关系……且效果不好，无法看清字幕，就算设置很慢也会一闪而过，无法同时出现或单独出现，会随机翻译，如正常顺序1234句对白，只翻译最后一句……而不是翻译全部
⬆我觉得这个插件跟您的文件似乎没关联……

4、我试着从上面这些插件找同类情况安放您给出的文件，但目前没成功运行出来过……我实在搞不懂您是怎么运行的

我昨天有去b站私信，刚刚查了github的用法，所以在这里给您留言？
希望您有空的时候可以回复我一下，非常感谢。

我再试着研究一下…………

**Comment by Yarukon** [comment]
我更新了README，请自行查阅
